// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHLM57BStx214mDibIXCIkqibQ4RIyLts',
    appId: '1:286715565538:web:ee704fee04331ff506d5bb',
    messagingSenderId: '286715565538',
    projectId: 'zaro-55798',
    storageBucket: 'zaro-55798.firebasestorage.app',
    authDomain: 'zaro-55798.firebaseapp.com',
    measurementId: 'G-HB8GVFKZZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAyWAUMSTqV7sXlSa-Kv8IWwmbjmOkALY',
    appId: '1:286715565538:android:e43f3a99fbfd1db806d5bb',
    messagingSenderId: '286715565538',
    projectId: 'zaro-55798',
    storageBucket: 'zaro-55798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdRKAqBCoCDipRcO8E_FccCgCuF6OyJO4',
    appId: '1:286715565538:ios:5844b3167febdc8406d5bb',
    messagingSenderId: '286715565538',
    projectId: 'zaro-55798',
    storageBucket: 'zaro-55798.firebasestorage.app',
    iosBundleId: 'com.jaywa.zaro',
  );
}
